### PR TITLE
Add spi-pio example

### PR DESCRIPTION
**Pull request by ithinuel**

### CODE REVIEW

**Comment by jannic** [comment]
I'm not sure if this makes a good example for inclusion in this repository. What does it show that's not already part of either pico_spi_sd_card or pico_i2c_pio?

It's basically a remix of the two ideas "access an SD card using the SPI peripheral"  and "you can replace physical peripherals by PIO". And I think it's not useful to have many of those examples, here.

**Comment by ithinuel** [comment]
That's true. I didn't include it as an example but merely as a way to validate it.

This could as well be an example in the spi-pio example (like the i2c-pio example, since we have the ws2812 example covering PIO).

**Comment by jannic** [comment]
Yes, having spi-pio is nice, and of course there should be an example. I just think that rp-hal-boards is not the best location.

**Comment by ithinuel** [comment]
moved to the spi-pio repo

**Pull request closed without merging**
