### PR TITLE
Display Driver and Example for Waveshare 1.28 Round LCD

### PR DESCRIPTION
**Pull request by GordonCox**
Example project for the Waveshare 1.28 Round LCD Display.  Renders simple graphics and displays a ticking second hand as a lock with the Rust logo as the background image.

### CODE REVIEW

**Comment by 9names** [comment]
Hi!
Your example program is pretty cool but it's also quite complex - do you think you could have something simpler [like the one for waveshare 0-96](https://github.com/rp-rs/rp-hal-boards/blob/main/boards/waveshare-rp2040-lcd-0-96/examples/waveshare_rp2040_lcd_demo.rs)

Also easier if an example fits in a single file - framebuffer.rs looks like it's another example, not a module used by an example.

There's also already a handful of crates that support gc8a01a, is there something your driver does that more established crates like mipidsi don't?

**Comment by 9names** [comment]
Also this has some build warnings, and the use of static mut's for your framebuffer is a concern:
```system
warning: crate-level attribute should be in the root module
 --> boards/waveshare-rp2040-lcd-1-28/examples/frame_buffer.rs:1:1
  |
1 | #![no_std]
  | ^^^^^^^^^^
  |
  = note: `#[warn(unused_attributes)]` on by default

warning: crate-level attribute should be in the root module
 --> boards/waveshare-rp2040-lcd-1-28/examples/frame_buffer.rs:2:1
  |
2 | #![no_main]
  | ^^^^^^^^^^^

warning: creating a mutable reference to mutable static is discouraged
   --> boards/waveshare-rp2040-lcd-1-28/examples/waveshare_rp2040_lcd_demo.rs:108:56
    |
108 |     let mut frame_buffer_1 = unsafe { FrameBuffer::new(&mut FRAME_BUFFER_1, LCD_WIDTH, LCD_HEIGHT) };
    |                                                        ^^^^^^^^^^^^^^^^^^^ mutable reference to mutable static
    |
    = note: for more information, see issue #114447 <https://github.com/rust-lang/rust/issues/114447>
    = note: this will be a hard error in the 2024 edition
    = note: this mutable reference has lifetime `'static`, but if the static gets accessed (read or written) by any other means, or any other reference is created, then any further use of this mutable reference is Undefined Behavior
    = note: `#[warn(static_mut_refs)]` on by default
help: use `addr_of_mut!` instead to create a raw pointer
    |
108 |     let mut frame_buffer_1 = unsafe { FrameBuffer::new(addr_of_mut!(FRAME_BUFFER_1), LCD_WIDTH, LCD_HEIGHT) };
    |                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by GordonCox** [comment]
I can simplify the example.  This specific example was created because the display is commonly used for watches so I made something that was also like a watch.  I will remove the complexities from it.

I created this display driver as it is a closer match to the one provided by Waveshare for their Python and C examples.  I wanted to explicitly show the configuration instructions of the display.  I commented the display instructions from the chipset where possible.  Some configuration instructions remain undocumented as Waveshare never provided details on them.

I will remove the framebuffer and simplify the example.  

I am happy to make the changes as this is the first project I have made with Rust.

**Comment by GordonCox** [comment]
All comments have been considered and new code has been committed for your review.

**Comment by GordonCox** [comment]
Are there any further outstanding issues, I updated the code so that the automatic checks would pass.  I learned a lot with those automatic checks and have added some into my own projects.

**Review by 9names — APPROVED** [review]

**Pull request merged**
